
<!-- Footer -->
<div class="footer-bar">
	<div class="container">
		
		<div class="row">
		
			<div class="span3">
			
				<p class="logo">Navigation</p>
				
				<ul>
					<li class="active"><a href="index.html">Home</a></li>
					<li><a href="1column.html">Tags</a></li>
					<li><a href="nosidebar.html">Latests</a></li>
					<li><a href="content.html">Search</a></li>
					<li><a href="contact.html">Contact Us</a></li>
				</ul>
				
			</div>
			
			<div class="span3">
			
				<p class="logo">About<span>Us</span></p>
				
				<p>Suspendisse diam urna, pretium eu eleifend vel, convallis quis libero.</p>
				
				<ul>
					<li class="active"><a href="content.html">Our Team</a></li>
					<li><a href="content.html">Write For Us</a></li>
					<li><a href="content.html">Our Network</a></li>
					<li><a href="contact.html">Contact Us</a></li>
				</ul>
				
			</div>
			
		</div>
	</div>
<!-- End Footer -->
</div>

<!-- Javascript -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="/assets/js/bootstrap.js"></script>
<script src="/assets/js/jquery.tweet.js"></script>
<script src="/assets/js/jflickrfeed.min.js"></script>
<script src="/assets/js/magazine.js"></script>

<!-- Document End -->
</body>
</html>
<!-- Localized -->